### ISSUE TITLE
Getting flutter error connecting to the service protocol:

### ISSUE THREAD

**Issue by wazini-john** [googleads/googleads-mobile-flutter#322]
## Plugin Version

google_mobile_ads: ^0.13.2

## Steps to Reproduce
Here are my dependencies

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.2.2
  cloud_functions: ^1.1.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.1.2
  firebase_app_check: ^0.0.1+3
  firebase_auth: ^1.4.1
  firebase_database: ^7.1.1
  firebase_dynamic_links: ^2.0.7
  firebase_remote_config: ^0.10.0-dev.1
  flutter_barcode_scanner: ^2.0.0
  flutter_hooks: ^0.16.0-nullsafety.0
  google_fonts: ^2.0.0
  # google_mobile_ads: ^0.13.2
  google_sign_in: ^5.0.4
  hooks_riverpod: ^0.14.0
  in_app_purchase: ^1.0.6
  intl: ^0.17.0
  package_info: ^2.0.0
  pay: ^1.0.4
  sign_in_with_apple: ^3.0.0
  version: ^2.0.0
```

Adding it to my app leads to `flutter error connecting to the service protocol:`
