### ISSUE TITLE
Added plugin to app, directly failed build after trying to run the app

### ISSUE THREAD

**Issue by Siyaho** [googleads/googleads-mobile-flutter#985]
The issue:
I am trying to implement the `Google AdMob plugin` into my Flutter app, but the build fails after doing `flutter run` as soon as I have installed the plugin. Of course, I first ran the install command, `flutter pub get` and flutter run (after `flutter clean`), but nothing works.

This is the **error** I am getting:
```
D:\Flutter\MYAPPNAME\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:24: error: package io.flutter.plugins.googlemobileads does not exist
      flutterEngine.getPlugins().add(new io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin());

                                                                           ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I even tried, as a last resort, to do this in `build.gradle`, but sadly no luck.
```
dependencies {
    implementation 'com.google.android.gms:play-services-ads:22.6.0'
}
```

**My pubspec.yaml:**

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  flutter_html: ^2.2.1
  get: ^4.6.6
  url_launcher: ^6.2.2
  html_unescape: ^2.0.0
  flutter_linkify: ^6.0.0
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  share_plus: ^6.3.4
  async: ^2.11.0
  flutter_native_splash: ^2.2.0+1
  google_mobile_ads: ^2.4.0
```

_(I also tried ^ 4.0.0, same issue)_

How can we solve this?
